# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/activerecord-honeycomb/all/activerecord-honeycomb.rbi
#
# activerecord-honeycomb-0.4.0
module ActiveRecord
end
module ActiveRecord::Honeycomb
end
module ActiveRecord::Honeycomb::AutoInstall
  def self.auto_install!(honeycomb_client:, logger: nil); end
  def self.available?(logger: nil); end
end
