# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/dm-postgres-adapter/all/dm-postgres-adapter.rbi
#
# dm-postgres-adapter-1.2.0
module DataMapper
end
module DataMapper::Adapters
end
class DataMapper::Adapters::PostgresAdapter < DataMapper::Adapters::DataObjectsAdapter
  extend DataMapper::Migrations::DataObjectsAdapter::ClassMethods
  extend DataMapper::Migrations::PostgresAdapter::ClassMethods
  include DataMapper::Adapters::PostgresAdapter::SQL
  include DataMapper::Constraints::Adapters::PostgresAdapter
  include DataMapper::Migrations::PostgresAdapter
  include DataMapper::Transaction::PostgresAdapter
end
module DataMapper::Adapters::PostgresAdapter::SQL
  def supports_returning?; end
end
