# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/dm-sqlite-adapter/all/dm-sqlite-adapter.rbi
#
# dm-sqlite-adapter-1.2.0
module DataMapper
end
module DataMapper::Adapters
end
class DataMapper::Adapters::SqliteAdapter < DataMapper::Adapters::DataObjectsAdapter
  def initialize(name, options); end
  def normalize_options(options); end
  def supports_subquery?(query, source_key, target_key, qualify); end
  extend DataMapper::Migrations::DataObjectsAdapter::ClassMethods
  extend DataMapper::Migrations::SqliteAdapter::ClassMethods
  include DataMapper::Constraints::Adapters::SqliteAdapter
  include DataMapper::Migrations::SqliteAdapter
  include DataMapper::Transaction::SqliteAdapter
end
