# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/dm-types/all/dm-types.rbi
#
# dm-types-1.2.2
module DataMapper
end
class DataMapper::Property
end
