# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/do_postgres/all/do_postgres.rbi
#
# do_postgres-0.10.17
class DataObjects::Postgres::Connection < DataObjects::Connection
  def character_set; end
  def dispose; end
  def initialize(arg0); end
  def quote_byte_array(arg0); end
  def quote_string(arg0); end
  def self.new(*args); end
  include DataObjects::Quoting
end
module DataObjects::Postgres
  def self.logger; end
  def self.logger=(logger); end
end
class DataObjects::Postgres::Command < DataObjects::Command
  def execute_non_query(*arg0); end
  def execute_reader(*arg0); end
  def set_types(*arg0); end
end
class DataObjects::Postgres::Reader < DataObjects::Reader
  def close; end
  def field_count; end
  def fields; end
  def next!; end
  def values; end
end
module DataObjects
end
class DataObjects::Postgres::Transaction < DataObjects::Transaction
  def begin; end
  def begin_prepared; end
  def commit; end
  def commit_prepared; end
  def prepare; end
  def rollback; end
  def rollback_prepared; end
end
module DataObjects::Postgres::Encoding
end
