# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/do_sqlite3/all/do_sqlite3.rbi
#
# do_sqlite3-0.10.17
class DataObjects::Sqlite3::Connection < DataObjects::Connection
  def character_set; end
  def dispose; end
  def initialize(arg0); end
  def quote_boolean(arg0); end
  def quote_byte_array(arg0); end
  def quote_string(arg0); end
  def self.new(*args); end
  include DataObjects::Quoting
end
module DataObjects::Sqlite3
  def self.logger; end
  def self.logger=(logger); end
end
class DataObjects::Sqlite3::Command < DataObjects::Command
  def execute_non_query(*arg0); end
  def execute_reader(*arg0); end
  def set_types(*arg0); end
end
class DataObjects::Sqlite3::Reader < DataObjects::Reader
  def close; end
  def field_count; end
  def fields; end
  def next!; end
  def values; end
end
class DataObjects::Sqlite3::Extension < DataObjects::Extension
  def enable_load_extension(arg0); end
  def load_extension(arg0); end
end
module DataObjects
end
class DataObjects::Sqlite3::Transaction < DataObjects::Transaction
  def begin_prepared; end
  def commit_prepared; end
  def prepare; end
  def rollback_prepared; end
end
