# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/faraday-honeycomb/all/faraday-honeycomb.rbi
#
# faraday-honeycomb-0.3.1
module Faraday
end
module Faraday::Honeycomb
end
module Faraday::Honeycomb::AutoInstall
  def self.auto_install!(honeycomb_client:, logger: nil); end
  def self.available?(logger: nil); end
end
