# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rack-honeycomb/all/rack-honeycomb.rbi
#
# rack-honeycomb-0.5.0
module Rack
end
module Rack::Honeycomb
end
module Rack::Honeycomb::AutoInstall
  def self.already_added; end
  def self.already_added=(arg0); end
  def self.already_warned; end
  def self.already_warned=(arg0); end
  def self.auto_install!(honeycomb_client:, logger: nil); end
  def self.auto_install_rails!(honeycomb_client, logger); end
  def self.auto_install_sinatra!(honeycomb_client, logger); end
  def self.available?(logger: nil); end
  def self.debug(msg); end
  def self.has_gem?(gem_name); end
  def self.warn(msg); end
end
