language: ruby
rvm:
  - 2.5.5
before_install:
  - gem update --system
  - gem install bundler
install:
  - bundle install --without production
script:
  - bundle exec rubocop
  - bundle exec rspec
  - bundle exec srb tc
