# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Coveralls; end
module ActiveSupport::ActionController::Base; end
module AuthInfo::Serial; end
module Menu::Serial; end
module Order::Serial; end
module User::Boolean; end
module User::Boolean; end
module User::Serial; end
module User::Serial; end
